version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    # Используем готовый образ PostgreSQL
    image: postgres:18-alpine
    container_name: express_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      # Постоянное хранение данных БД в Docker томе под названием postgres_data
      - postgres_data:/var/lib/postgresql/data
    networks:
      # Подключаем к общей сети приложения
      - app-network
    healthcheck:
      # Проверка доступности БД, которую docker-compose делает самостоятельно
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-appuser}']
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin для управления БД через браузер (опционально, но полезно для обучения)
  pgadmin:
    # Используем готовый образ pgAdmin
    image: dpage/pgadmin4
    container_name: express_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '5050:80'
    # Зависимость от сервиса postgres, чтобы pgAdmin запускался после БД
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  # Панель управления уже самой ORM Prisma
  prisma-studio:
    # Собираем тот же образ, что и для приложения, но запускаем Prisma Studio а не Express
    build: .
    container_name: express_prisma_studio
    ports:
      - '5555:5555'
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    volumes:
      # Подключаем к общему тому приложения, чтобы изменения внутри контейнера сохранялись
      - .:/app
      # Node modules подключаем к анонимному тому (не указываем его), таким образом node_modules будут существовать только пока контейнер запущен
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: npx prisma studio --port 5555 --browser none
    networks:
      - app-network

  app:
    build: .
    container_name: express_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    command: yarn dev
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:8000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

# Определяем общую сеть
networks:
  app-network:
    driver: bridge

# Данные базы данных будут храниться в отдельном Docker томе
volumes:
  postgres_data:
